config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  devise_for :users do
    resources :boards
  end

  resources :boards do
    resources :lists
  end

  resources :lists do
    resources :cards
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :cards
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :destroy, :update]

  def index
    @boards = Board.all
  end

  def show
    @lists = @board.lists.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @board = Board.new(board_params)
    if @board.update
      redirect_to boards_path
    else
      render :edit
    end
  end

  

  def destroy
  end

  private

  def set_board 
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_list
  before_action :set_card, only: [:edit, :update, :destroy]

  def new
    @cards = @list.cards.new
  end

  def create
    @list.cards.create_card(cards_params, @list.id)
    redirect_to board_path(@list.board_id)
  end

  def edit
  end

  def update
    Task.update_card(@card.id, card_params)
    redirect_to board_path(@list.board_id)
  end

  def destroy
      @board = Board.find(@list.board_id)
      @task.destroy
      redirect_to board_list_path(@board, @list)
  end
end

  private
    def set_card
      @card = Card.single_card(params[:id])
    end

    def set_list
      @list = List.single_list(params[:list_id])
    end

    def card_params
      params.require(:card).permit(:title, :description,)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board, only: [:new, :create, :edit, :update]
  before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @lists = @board.lists.new
  end

  def create
    @board.lists.create_list(list_params, @board.id)
    redirect_to @board
  end

  def edit
  end

  def update
    List.update_list(@list.id, list_params)
    redirect_to @board
  end

  def destroy
    @list.destroy
    redirect_to board_path(@list.board_id)
  end

  private
    def set_list
      @list = List.single_list(params[:id])
    end

    def set_board
      @board = Board.single_board(params[:board_id])
    end

    def list_params
      params.require(:list).permit(:name)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/index.html.erb
<div class= "board index">
  <div class="ui animated fade inverted grey button" tabindex="0">
  <div class="visible content">Personal Boards</div>
  <div class="hidden content">
   <%= link_to 'Add Board', new_board_path %>
  </div>
</div> 
</hr>
</hr>
 
<div class="ui equal width center aligned padded grid" style= "color: red;">
  <% @boards.each do |board| %>
    <div class="four wide column">
      <div class="ui raised center aligned segment">
        <%= link_to board.name, board_path(board), class:"board"%>    
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/boards/new.html.erb
<h1>Add Board</h1>
<%= form_with(model: @board, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Board Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>
 

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>
<%= link_to "Edit", edit_board_path(@board), class: "ui orange button inverted" %>
<%= link_to "Delete", @board, method: :delete, class: "ui red button inverted" %>
<%= link_to "New List", new_board_list_path(@board), class:"ui green button inverted"%>


<hr />
<div class="ui grid">
  <% @board.lists.each do |list| %>
    <div class="five wide column">
      <div class="ui raised center aligned red segment">
          <h3><%= list.name %></h3>
          <%= link_to "New Card", new_list_card_path(list), class:"ui mini green button inverted"%>
          <hr/>
            <% list.tasks.sort_by.each do |card| %>
              <div class="five wide column">
                <div class="ui raised center aligned blue segment">
                  <h3><%= task.name %></h3>
                  <hr/>
                  <p><%= task.description %></p>
                  <%= link_to "Edit", edit_list_task_path(task.list_id, task.id), class: "ui mini orange button inverted" %>
                  <%= link_to "Delete", list_card_path(card.list_id, card.id), method: :delete, class: "ui mini red button inverted" %>
                </div>
              </div>
              <hr/>
            <%end%>
          <%= link_to "Edit", edit_board_list_path(list.board_id, list.id), class: "ui mini orange button inverted" %>
          <%= link_to "Delete", list, method: :delete, class: "ui mini red button inverted" %>
      </div>
    </div>
  <% end %>
</div>

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>
<p>Find me in app/views/cards/edit.html.erb</p>

app/views/cards/index.html.erb
<h1>Cards#index</h1>
<p>Find me in app/views/cards/index.html.erb</p>

app/views/cards/new.html.erb
<h1>Cards#new</h1>
<p>Find me in app/views/cards/new.html.erb</p>

app/views/cards/show.html.erb
<h1>Cards#show</h1>
<p>Find me in app/views/cards/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
  <%= image_tag 'Trello-logo-grey.png', class:"logo"%>
  <div class="right menu">
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
      <%= link_to "Home", user_session_path, class: "item" %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="body">
    <%= render "layouts/navbar" %>
      <div class ="ui container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>